mindmap
  root((Python))
    Legibility
      example(Uso de espacios en lugar de llaves)
      benefit(Fácil comprensión del código)
    Versatility
      example(Aplicaciones variadas)
      benefit(Aplicación en diferentes campos)
    "Ampia biblioteca estándar"
      example(Módulo os)
      benefit(Ahorro de tiempo)
    "Interpretado y tipado dinámico"
      example(Código ejecutado línea por línea)
      benefit(Facilidad de depuración)
    "Comunidad y soporte"
      example(Bibliotecas y frameworks contribuidos)
      benefit(Amplio soporte y recursos)